/**
 *
 * @author 2004rend
 */
package sistemadecontrol.view;

import javax.swing.*;
import java.awt.*;

// Ventana de inicio de sesion del sistema
public class LoginFrame extends JFrame {

    // Componentes publicos para que el controlador acceda a ellos
    public JTextField txtUsuario;
    public JPasswordField txtClave;
    public JButton btnIngresar;
    public JLabel lblMensaje;

    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setTitle("Sistema de Control - Iniciar Sesion");
        setSize(380, 280);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        // Panel principal con margen interno
        JPanel panelPrincipal = new JPanel(new BorderLayout(10, 10));
        panelPrincipal.setBorder(BorderFactory.createEmptyBorder(25, 35, 25, 35));
        panelPrincipal.setBackground(new Color(245, 245, 250));

        // Titulo del login
        JLabel lblTitulo = new JLabel("Control de Pedidos", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblTitulo.setForeground(new Color(50, 50, 70));
        panelPrincipal.add(lblTitulo, BorderLayout.NORTH);

        // Panel del formulario
        JPanel panelFormulario = new JPanel(new GridLayout(2, 2, 8, 12));
        panelFormulario.setOpaque(false);

        JLabel lblUsuario = new JLabel("Usuario:");
        lblUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        JLabel lblClave = new JLabel("Contraseña:");
        lblClave.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        txtUsuario = new JTextField();
        txtUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        txtClave = new JPasswordField();
        txtClave.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        panelFormulario.add(lblUsuario);
        panelFormulario.add(txtUsuario);
        panelFormulario.add(lblClave);
        panelFormulario.add(txtClave);

        panelPrincipal.add(panelFormulario, BorderLayout.CENTER);

        // Panel inferior con boton y mensaje
        JPanel panelInferior = new JPanel(new BorderLayout(0, 8));
        panelInferior.setOpaque(false);

        btnIngresar = new JButton("Ingresar");
        btnIngresar.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnIngresar.setBackground(new Color(70, 130, 180));
        btnIngresar.setForeground(Color.BLACK);
        btnIngresar.setFocusPainted(false);
        btnIngresar.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblMensaje = new JLabel("Ingrese sus credenciales", SwingConstants.CENTER);
        lblMensaje.setFont(new Font("Segoe UI", Font.ITALIC, 11));
        lblMensaje.setForeground(Color.GRAY);

        panelInferior.add(btnIngresar, BorderLayout.NORTH);
        panelInferior.add(lblMensaje, BorderLayout.SOUTH);

        panelPrincipal.add(panelInferior, BorderLayout.SOUTH);

        add(panelPrincipal);
    }
    // </editor-fold>
}
